openapi: 3.0.0
info:
  title: Ping API
  version: 1.0.0
  servers:
    - url: "http://localhost:8000"
paths:
  /ping:
    get:
      summary: Ping endpoint
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
              example: pong